var url,videoId,isLoaded=!1,privateMode=!1,videoIdExtractor=/(http(?: s) ?: \/\/(?:m.)?(?:www\.)?)?youtu(?:\.be\/|be\.com\/(?:watch\?(?:feature=youtu\.be&)?v=|v\/|embed\/|user\/(?:[\w#]+\/)+))([^&#?\n]+)/,urlValidator=/((https(?:s)?:\/\/)?(www\.)?)?(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?&v=))((?:\w|-){11})((?:&|\?)\S*)?/,whiteSpaceValidator=/\s/g;
function getVideoURL(){var a=whiteSpaceValidator.test(url);url=prompt("Insert the URL of the video you want to watch");a&&url.replace(/\s/g,"");validateURL(url)}function validateURL(a){urlValidator.test(a)||0===a.length||void 0===a?getId(a):(alert("Invalid URL\nTry Again"),refresh(),getVideoURL())}function getId(a){videoId=videoIdExtractor.exec(a)[2];loadVideo(videoId);return videoId}
function loadVideo(a){document.getElementById("overlay").style.display="block";document.querySelector("#uiLoader1").style.display="flex";privateMode?document.getElementById("videoPlayer").src="https://www.youtube-nocookie.com/embed/"+a:document.getElementById("videoPlayer").src="https://www.youtube.com/embed/"+a;document.querySelector("iframe").onload=function(){document.getElementById("overlay").style.display="none";isLoaded=!0;document.getElementById("videoPlayer").focus()}}
function openFullscreen(){var a=document.getElementById("videoPlayer");0!==a.src.length&&isLoaded?a.requestFullscreen?a.requestFullscreen():a.webkitRequestFullscreen?a.webkitRequestFullscreen():a.msRequestFullscreen?a.msRequestFullscreen():alert("Unable to open video in full screen"):(console.log("Error: unable to toggle full screen\nReason: no URL found"),alert("We are unable to toggle full screen if a video hasn't been loaded\nPlease enter a URL first"),getVideoURL())}
function refresh(){url="";document.getElementById("videoPlayer").src="";return isLoaded=!1}function shareVideo(){void 0!==videoId?(navigator.clipboard.writeText("https://youtu.be/"+videoId),alert("Link copied to clipboard")):(console.log("Error: unable to copy shortened URL to clipboard\nReason: no URL found"),alert("You haven't entered a URL to share\nPlay a video and try again"),getVideoURL())}
function help(){alert("Thanks for using YT Player!\nUse the play icon to start watching videos, the full screen icon to play videos in full screen, the refresh button to reset the player,the lock to play videos in Private Mode, and the open button to open the video in a new tab.\nButtons that are grayed out are disabled and buttons that are black are enabled\nMade with \u2764\ufe0f by UnrealApex\nThank you to all those who helped improve this project!")}
function openVideoInNewTab(){isLoaded?window.open("https://www.youtube.com/watch?v="+videoId,document.title,"toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width=1000, height=900, top="+(screen.height/2-450)+", left="+(screen.width/2-500)):(console.log("Error: unable to open video in new tab\nReason: no URL found"),alert("We can't open video in new tab because you haven't entered a URL\n Play a video and try again"),getVideoURL())}
function togglePrivateMode(){privateMode?privateMode?(document.getElementById("private-mode").style.opacity="38%",document.getElementById("private-mode").setAttribute("title","Toggle Private Mode, Private Mode is off, toggling will enable Private Mode"),privateMode=!1):console.log("Unable to toggle private mode"):(document.getElementById("private-mode").style.opacity="100%",document.getElementById("private-mode").setAttribute("title","Toggle Private Mode, Private Mode is enabled."),privateMode=!0);
return privateMode}
